INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Coconut Coffee', 38000, 'Robusta coffee blended with coconut milk', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Egg Coffee', 42000, 'Vietnamese egg yolk whipped with condensed milk and robusta', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Iced Peach Tea', 33000, 'Black tea with peach syrup and peach slices', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Matcha Latte', 45000, 'Japanese matcha with steamed milk', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Mocha', 42000, 'Espresso with chocolate syrup and milk', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Iced Americano', 30000, 'Espresso diluted with ice water', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Caramel Macchiato', 47000, 'Espresso with milk foam and caramel sauce', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Oolong Milk Tea', 37000, 'Oolong tea with milk and boba', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Taro Milk Tea', 37000, 'Taro-flavored milk tea with chewy boba', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Thai Green Milk Tea', 36000, 'Green Thai tea with milk', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Orange Juice', 29000, 'Freshly squeezed orange juice', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Lemon Tea', 25000, 'Black tea with fresh lemon juice', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Yogurt with Passion Fruit', 28000, 'Chilled yogurt with passion fruit syrup', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Strawberry Smoothie', 39000, 'Strawberry blended with ice and condensed milk', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Avocado Smoothie', 42000, 'Fresh avocado with condensed milk and crushed ice', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Mango Smoothie', 39000, 'Ripe mango blended with milk', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Choco Ice Blended', 45000, 'Chocolate powder with milk and ice', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Matcha Ice Blended', 46000, 'Matcha green tea blended with milk and ice', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Peach Soda', 34000, 'Soda water with peach syrup and ice', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Mint Soda', 34000, 'Refreshing soda with mint syrup', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Butter Croissant', 27000, 'Classic croissant with buttery layers', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Cheese Danish', 29000, 'Pastry filled with cream cheese', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Tuna Sandwich', 42000, 'Whole wheat bread with tuna and veggies', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Chicken Sandwich', 43000, 'Grilled chicken with mayo and lettuce', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Bacon & Egg Toast', 40000, 'Toast topped with bacon and sunny egg', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Egg & Cheese Bagel', 38000, 'Toasted bagel with scrambled egg and cheese', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Ham and Cheese Panini', 45000, 'Grilled sandwich with ham and melted cheese', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Pasta Carbonara', 49000, 'Creamy spaghetti with bacon and cheese', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Pasta Bolognese', 50000, 'Spaghetti with beef tomato sauce', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'French Fries', 30000, 'Crispy golden French fries', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Hash Brown', 25000, 'Fried shredded potato patty', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Fruit Salad', 35000, 'Seasonal fresh fruits in a cup', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Bánh Flan', 20000, 'Vietnamese caramel custard dessert', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Chè Khúc Bạch', 35000, 'Almond jelly with lychee and syrup', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Coconut Jelly', 32000, 'Soft jelly made from coconut milk', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Soda Blue Ocean', 34000, 'Blue curacao syrup with soda', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Espresso', 30000, 'Strong concentrated black coffee shot', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Cappuccino', 42000, 'Espresso with steamed milk and foam', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Flat White', 43000, 'Double shot espresso with microfoam', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Green Tea Latte', 40000, 'Green tea brewed with milk', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Rose Milk Tea', 37000, 'Milk tea infused with rose flavor', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Brown Sugar Boba', 38000, 'Milk tea with brown sugar tapioca pearls', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Lime Soda', 33000, 'Soda with fresh lime and syrup', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Honey Lemon Tea', 31000, 'Black tea with honey and lemon', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Salted Coffee', 32000, 'Cà phê muối truyền thống Huế', 'Unavailable');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Cold Brew', 35000, 'Coffee steeped in cold water overnight', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Pumpkin Spice Latte', 48000, 'Seasonal espresso drink with pumpkin and spices', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Vietnamese Iced Coffee', 32000, 'Cà phê sữa đá pha phin', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Lychee Tea', 34000, 'Trà vải thanh mát với vải thật', 'Available');
INSERT INTO MenuItem VALUES (MenuItem_seq.NEXTVAL, 'Oreo Ice Blended', 47000, 'Crushed Oreo cookies with milk and ice', 'Available');