/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.coffeemate.component;

import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author meiln
 */
public class Sidebar extends javax.swing.JPanel 
{
    public interface MenuSelectionListener {
        void onMenuSelected(String menuKey);
    }

    private MenuSelectionListener menuListener;

    public Sidebar() {
        setOpaque(false);
        initComponents();      
    }


public void setMenuSelectionListener(MenuSelectionListener listener) {
    this.menuListener = listener;
}
@Override
public void addNotify() {
    super.addNotify();
   
}

   @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Vẽ gradient background cho header
        Graphics2D g2d = (Graphics2D) g;
        GradientPaint gradient = new GradientPaint(
                0, 0, new Color(0, 123, 255), // Bắt đầu màu xanh dương
                0, getHeight(), new Color(0, 102, 204) // Kết thúc màu xanh đậm
        );
        g2d.setPaint(gradient);
        g2d.fillRect(0, 0, getWidth(), getHeight()); // Vẽ gradient nền
    }

  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupMenu = new javax.swing.ButtonGroup();
        jbtnDashboard = new javax.swing.JToggleButton();
        jbtnEmployee = new javax.swing.JToggleButton();
        jbtnMenu = new javax.swing.JToggleButton();
        jbtnStock1 = new javax.swing.JToggleButton();

        btngroupMenu.add(jbtnDashboard);
        jbtnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/coffeemate/resources/ic_dashboard.png"))); // NOI18N
        jbtnDashboard.setText("Dashboard");
        jbtnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDashboardActionPerformed(evt);
            }
        });

        btngroupMenu.add(jbtnEmployee);
        jbtnEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/coffeemate/resources/ic_employee.png"))); // NOI18N
        jbtnEmployee.setText("Nhân viên");
        jbtnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmployeeActionPerformed(evt);
            }
        });

        btngroupMenu.add(jbtnMenu);
        jbtnMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/coffeemate/resources/ic_menu.png"))); // NOI18N
        jbtnMenu.setText("Menu");
        jbtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenuActionPerformed(evt);
            }
        });

        btngroupMenu.add(jbtnStock1);
        jbtnStock1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnStock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/coffeemate/resources/ic_salary.png"))); // NOI18N
        jbtnStock1.setText("Hóa đơn");
        jbtnStock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStock1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDashboard)
                    .addComponent(jbtnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jbtnDashboard)
                .addGap(35, 35, 35)
                .addComponent(jbtnMenu)
                .addGap(43, 43, 43)
                .addComponent(jbtnEmployee)
                .addGap(44, 44, 44)
                .addComponent(jbtnStock1)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenuActionPerformed
        if (menuListener != null) menuListener.onMenuSelected("MENU");

    }//GEN-LAST:event_jbtnMenuActionPerformed

    private void jbtnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDashboardActionPerformed
        if (menuListener != null) menuListener.onMenuSelected("DASHBOARD");
    }//GEN-LAST:event_jbtnDashboardActionPerformed

    private void jbtnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmployeeActionPerformed
        if (menuListener != null) menuListener.onMenuSelected("EMPLOYEE");
    }//GEN-LAST:event_jbtnEmployeeActionPerformed

    private void jbtnStock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStock1ActionPerformed
               if (menuListener != null) menuListener.onMenuSelected("INVOICE");
 // TODO add your handling code here:
    }//GEN-LAST:event_jbtnStock1ActionPerformed

       @Override
    public Dimension getPreferredSize() {
        return new Dimension(getParent() != null ? getParent().getWidth() : 800, 70);
    }

    @Override
    public void doLayout() {
        super.doLayout();
        revalidate();
        repaint();
    }
   private void resizeButtons() {
        int totalHeight = getHeight();
        int buttonCount = 5;
        int margin = 10;
        int availableHeight = totalHeight - (margin * (buttonCount + 1));
        int buttonHeight = availableHeight / buttonCount;

        JToggleButton[] buttons = {
            jbtnDashboard, jbtnMenu, jbtnEmployee, 
        };

        for (JToggleButton btn : buttons) {
            btn.setPreferredSize(new Dimension(getWidth() - 20, buttonHeight));
            btn.setMaximumSize(new Dimension(getWidth() - 20, buttonHeight));
            btn.setMinimumSize(new Dimension(getWidth() - 20, buttonHeight));
            btn.setFont(new Font("Segoe UI", Font.BOLD, Math.max(12, buttonHeight / 4)));
        }
        revalidate();
        repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroupMenu;
    private javax.swing.JToggleButton jbtnDashboard;
    private javax.swing.JToggleButton jbtnEmployee;
    private javax.swing.JToggleButton jbtnMenu;
    private javax.swing.JToggleButton jbtnStock1;
    // End of variables declaration//GEN-END:variables
}
