/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.coffeemate.view;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author meiln
 */
public class AdminView extends javax.swing.JFrame {
    private CardLayout cardLayout;

 
        public AdminView() {
    try {
        // Set system look and feel
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        initComponents();
        initCustomComponents();

      
        setMinimumSize(new Dimension(800, 600)); // Có thể đặt kích thước tối thiểu
        setLocationRelativeTo(null); // Canh giữa màn hình
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Mở rộng toàn màn hình ban đầu
        setVisible(true); // Đảm bảo hiển thị ngay

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khởi tạo giao diện: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}


    private void initCustomComponents() {
        cardLayout = (CardLayout) CardPanel.getLayout();
        CardPanel.add(new MenuPanel(), "MENU");
        CardPanel.add(new EmployeePanel(), "EMPLOYEE");

        cardLayout.show(CardPanel, "MENU");

        sidebar.setMenuSelectionListener(menuKey -> {
            cardLayout.show(CardPanel, menuKey);
        });
    }
    
       



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashierHeader = new com.coffeemate.component.CashierHeader();
        DisplayPanel = new javax.swing.JPanel();
        sidebar = new com.coffeemate.component.Sidebar();
        jspAdmin = new javax.swing.JScrollPane();
        CardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cashierHeader.setMinimumSize(new java.awt.Dimension(170, 40));
        getContentPane().add(cashierHeader, java.awt.BorderLayout.PAGE_START);

        CardPanel.setLayout(new java.awt.CardLayout());
        jspAdmin.setViewportView(CardPanel);

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jspAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE))
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)))
        );

        getContentPane().add(DisplayPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        EventQueue.invokeLater(() -> {
            LoginForm view = new LoginForm();
            view.setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardPanel;
    private javax.swing.JPanel DisplayPanel;
    private com.coffeemate.component.CashierHeader cashierHeader;
    private javax.swing.JScrollPane jspAdmin;
    private com.coffeemate.component.Sidebar sidebar;
    // End of variables declaration//GEN-END:variables
}
