/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.coffeemate.view;
import com.coffeemate.controller.EmployeeController;
import com.coffeemate.model.Employee;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author meiln
 */
public class EmployeeView extends javax.swing.JFrame {
 private EmployeeController employeeController;  // Khai báo controller
    /**
     * Creates new form EmployeeView
     */
    public EmployeeView() {
        initComponents();
        employeeController = new EmployeeController();  // Khởi tạo controller
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupCRUD = new javax.swing.ButtonGroup();
        lblTableTitle = new javax.swing.JLabel();
        btnCreate = new javax.swing.JToggleButton();
        btnDelete = new javax.swing.JToggleButton();
        btnUpdate = new javax.swing.JToggleButton();
        btnRead = new javax.swing.JToggleButton();
        spCRUDTable = new javax.swing.JScrollPane();
        tbEmployee = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTableTitle.setText("Bảng nhân viên");

        btngroupCRUD.add(btnCreate);
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/coffeemate/resources/ic_create.png"))); // NOI18N
        btnCreate.setText("Thêm");
        btnCreate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btngroupCRUD.add(btnDelete);
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/coffeemate/resources/ic_delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btngroupCRUD.add(btnUpdate);
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/coffeemate/resources/ic_update.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btngroupCRUD.add(btnRead);
        btnRead.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/coffeemate/resources/ic_search.png"))); // NOI18N
        btnRead.setText("Tìm kiếm");
        btnRead.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRead.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        tbEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ tên", "Vai trò", "SDT", "Email", "Ngày tham gia"
            }
        ));
        spCRUDTable.setViewportView(tbEmployee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spCRUDTable)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCreate)
                        .addGap(43, 43, 43)
                        .addComponent(btnDelete)
                        .addGap(48, 48, 48)
                        .addComponent(btnUpdate)
                        .addGap(53, 53, 53)
                        .addComponent(btnRead))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(lblTableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreate)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnRead))
                .addGap(18, 18, 18)
                .addComponent(spCRUDTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        loadEmployeeData();
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      int row = tbEmployee.getSelectedRow();
        if (row != -1) {
            int employeeId = (int) tbEmployee.getValueAt(row, 0);
            boolean success = employeeController.deleteEmployee(employeeId);
            if (success) {
                JOptionPane.showMessageDialog(this, "Nhân viên đã được xóa!");
                loadEmployeeData(); // Cập nhật dữ liệu sau khi xóa
            } else {
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thất bại!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // Tạo và hiển thị form nhập dữ liệu nhân viên mới
        Employee employee = new Employee();
        employee.setFullName("Nguyễn Văn A");  // Chỉ là ví dụ, bạn có thể lấy từ form
        employee.setRole("Manager");
        employee.setPhone("0901234567");
        employee.setEmail("nva@gmail.com");
        employee.setHireDate(new java.util.Date());
        
        // Gọi controller để thêm nhân viên
        boolean success = employeeController.addEmployee(employee);
        if (success) {
            JOptionPane.showMessageDialog(this, "Nhân viên đã được thêm thành công!");
            loadEmployeeData(); // Cập nhật dữ liệu sau khi thêm
        } else {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại!");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
   int row = tbEmployee.getSelectedRow();
    if (row != -1) {
        int employeeId = (int) tbEmployee.getValueAt(row, 0);
        Employee employee = employeeController.getEmployeeById(employeeId);

        // Sau khi lấy thông tin nhân viên, bạn có thể hiển thị thông tin này lên form sửa
        if (employee != null) {
            employee.setPhone("0907654321"); // Ví dụ sửa số điện thoại
            boolean success = employeeController.updateEmployee(employee);
            if (success) {
                JOptionPane.showMessageDialog(this, "Nhân viên đã được cập nhật!");
                loadEmployeeData(); // Cập nhật dữ liệu sau khi sửa
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thất bại!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần sửa!");
    }

    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeView().setVisible(true);
            }
        });
    }


    // Hàm tải và hiển thị dữ liệu nhân viên vào bảng
    private void loadEmployeeData() {
        List<Employee> employees = employeeController.getAllEmployees();
        DefaultTableModel model = (DefaultTableModel) tbEmployee.getModel();
        model.setRowCount(0);  // Xóa các hàng cũ

        for (Employee emp : employees) {
            model.addRow(new Object[]{
                emp.getEmployeeID(), 
                emp.getFullName(), 
                emp.getRole(), 
                emp.getPhone(), 
                emp.getEmail(), 
                emp.getHireDate()
            });
        }
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCreate;
    private javax.swing.JToggleButton btnDelete;
    private javax.swing.JToggleButton btnRead;
    private javax.swing.JToggleButton btnUpdate;
    private javax.swing.ButtonGroup btngroupCRUD;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JScrollPane spCRUDTable;
    private javax.swing.JTable tbEmployee;
    // End of variables declaration//GEN-END:variables
}
